version: '3.7'
services:
  admin-portal:
    container_name: 'psa-admin-portal-self'
    build:
      context: .
      target: 'develop-stage'
    ports:
    - '8080:8080'
    volumes:
    - '.:/app'
    command: /bin/sh -c "yarn && quasar dev"